### ISSUE TITLE
Node-Sass dependency

### ISSUE THREAD

**Issue by SkothaSec** [BrokeDesign/BrokeReact#8]
**Describe the bug**
@imnas  noticed this one
On importing the NPM module, if user doesn't have node-sass installed, issues arise

**To Reproduce**
1. npm i @brokeds/broke-react
2. start the server
3. Error from sass not being loaded

**Expected behavior**
User is expected to have node-sass installed to make use of the package, should be a peer dependency to warn user if not already installed in their project.

**Tasks**
- [x] add node-sass as peer and dev dependency
- [x] while at it move jest & jest-resolve dependency to dev dependency, there is no reason for the user to need these.
- [x] publish update as an npm patch.
